### ISSUE TITLE
NPM install missing distribution directory

### ISSUE THREAD

**Issue by MDBox** [scalar-labs/scalardl-web-client-sdk#12]
I think `npm install @scalar-labs/scalardl-web-client-sdk` should include the `scalardl-web-client-sdk.bundle.js`. The current included files required a webpack enabled project which might not always be the case.  

I suggest the `make dist` output should be included in the npm bundle.

**Comment by scalarindetail** [comment]
@MDBox Thank you for your reminders
I forgot to consider the case in which developers might statically use the bundle after npm install.
I propose a bugfix PR in #13, please kindly advise.
