### ISSUE TITLE
ClientService requires unnecessary properties for serialized request creation

### ISSUE THREAD

**Issue by Torch3333** [scalar-labs/scalardl-web-client-sdk#33]
When using the ClientService to only create serialized request, the following properties are required upon the ClientService instantiation even though these properties are unnecessary.
```
ClientPropertiesField.SERVER_HOST,
ClientPropertiesField.SERVER_PORT,
ClientPropertiesField.SERVER_PRIVILEGED_PORT
```

**Comment by supl** [comment]
I just realize why we set these three properties as mandatory.
We need to pass the URL to the constructors when we create gRPC stubs (LedgerClient and LedgerPriviledgeClient).
For cases that developers only need to create serialized requests, I guess we can set the URL to empty strings.
Let me do a test for that.

**Comment by feeblefakie** [comment]
@Torch3333 @supl Thank you !
